server:
  port: 8888
spring:
  application:
    name: JHONATHAN-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhontahan/jhonathan-config-server
          default-label: main
          search-paths:
          - 'greeting-service*'
          #username: username
          #password: password